# Site settings
title: "aa830's GitHub"
description: "Some coding stuff I do"
url: "https://aa830.github.io" # Your GitHub Pages URL
baseurl: "" # Leave empty if in the root directory

# Owner/author information
author:
  name: "aa830"
  email: "aarvd2030@gmail.com"
  url: "https://aa830.github.io" # Link to your site or another profile

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed # RSS feed generator

# GitHub Pages settings
github:
  is_project_page: false # Set to true if this is a project site instead of a user/organization site

# SEO settings
permalink: "/:year/:month/:day/:title/" # Pretty URLs with date
paginate: 5 # Number of posts per page in pagination

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock

# Including CSS files
include:
  - assets/css/style.css

# Theme configuration
theme: minima # Using the Minima theme (you can customize it with your own CSS)

# Social media (optional)
social_links:
  github: "https://github.com/aa830"

# Minima theme settings (overrides)
minima:
  skin: dark # Using the dark mode for Minima theme
  header_color: "#232136" # Custom color for the header
  accent_color: "#569fba" # Accent color for links/buttons
  font_family:
    base: "'MonoLisa', sans-serif" # Use MonoLisa as the base font
    headings: "'MonoLisa', sans-serif"
    monospace: "'MonoLisa', monospace"
