# _config.yml

# Site settings
title: "aa830's github"
description: "some coding stuff I do"
url: "https://aa830.github.io" # Your GitHub Pages URL
baseurl: "" # The subpath of your site, e.g., /blog (leave empty if in the root directory)

# Owner/author information
author:
  name: "aa830"
  email: "aarvd2030@gmail.com"
  url: "https://aa830.github.io" # Link to your site or another profile

# Build settings
markdown: kramdown
theme: minima # Default theme provided by Jekyll
plugins:
  - jekyll-feed   # RSS feed generator

# GitHub Pages settings
github:
  is_project_page: false # Set to true if this is a project site instead of a user/organization site

# SEO settings
permalink: "/:year/:month/:day/:title/" # Pretty URLs with date
paginate: 5 # Number of posts per page in pagination

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock

# Social media (optional)
social_links:
  github: "https://github.com/aa830"
